### ISSUE TITLE
Django: Dependency management

### ISSUE THREAD

**Issue by lemonsaurus** [python-discord/site#186]
The Django branch has done away with `pipenv` in favor of a `setup.py` and just setting up environments manually.

I understand that this is far faster for builds, but in my opinion that advantage comes at the cost of convenience. I also don't love that it's inconsistent with our dependency management for `bot`. 

I'd like to hear more opinions about this though. It is a shame that pipenv is slowing down our builds by several orders of magnitude, but I do think that there is a solution for this to be found in some sort of clever caching, and I also don't know if 10 minute build times is a real problem.

**Comment by sco1** [comment]
Would it be worth investigating Poetry as an alternative to Pipenv?

**Comment by lemonsaurus** [comment]
Certainly worth investigating. If it provides the same utility as pipenv and has faster build times in a docker container, I'd be all for it.

**Comment by jb3** [comment]
I copied across all the dependencies from the setup.py file into an example pyproject.toml which looks like this:
```toml
[tool.poetry]
name = "pydis-site"
version = "0.1.0"
description = "Django application for the Python Discord server."
authors = ["Your Name <you@example.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"
django = "^2.1"
djangorestframework = "^3.9"
djangorestframework-bulk = "^0.2.1"
django-crispy-forms = "^1.7"
django-hosts = "^3.0"
django-environ = "^0.4.5"
django-filter = "^2.1"
psycopg2-binary = "^2.7"
uwsgi = "^2.0"

[tool.poetry.dev-dependencies]
flake8 = "^3.7"
flake8-bandit = "^2.1"
flake8-bugbear = "^18.8"
flake8-import-order = "^0.18.0"
flake8-string-format = "^0.2.3"
flake8-tidy-imports = "^2.0"
pep8-naming = "^0.8.0"
mccabe = "^0.6.1"
coverage = "^4.5"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
```

When running `poetry install` from no virtualenv it takes 1 minute and 4 seconds on my MacBook to install all the production dependencies and 1 minute 14 seconds to install the dev dependencies as well (I may have some caching going on but I tried to eliminate it).

**Comment by lemonsaurus** [comment]
should be tested inside a docker, ideally.

**Comment by jb3** [comment]
will give it a try now 👌

**Comment by jb3** [comment]
@heavysaturn docker test complete. Assuming that the `python:latest` image was cached it took 2 minutes and 56 seconds to install poetry as well as deps & dev deps.

Dockerfile here:
```dockerfile
FROM python:latest

COPY . /app
WORKDIR /app

RUN pip install poetry

RUN poetry install

CMD ["python", "-m", "application"]
```

**Comment by lemonsaurus** [comment]
yeah that seems pretty fast. how does it compare to pipenv in usability? is the `[tool.poetry]` section meant to be able to replace the setup.py file for stuff like pypi deployments?

**Comment by jerbob** [comment]
Yeah, according to [their README](https://github.com/sdispater/poetry#why), it looks like they intend to replace setup.py, requirements.txt, setup.cfg, MANIFEST.in and Pipfile. I've used poetry for a couple of projects, and can confirm that it's super easy to publish stuff to pypi (`poetry publish`). All we really need is the `pyproject.toml` and optionally a `poetry.lock`.

**Comment by lemonsaurus** [comment]
that's cool, and perhaps we should consider using it for our PyPI django packages if it works well.

Anyway, I'd be okay with testing out poetry for this project, I guess. if it works well for us, we might consider replacing pipenv with poetry in our other projects.

Does anyone happen to remember why we were so opposed to poetry back in the day?

**Comment by jerbob** [comment]
As for usability, I haven't really used poetry for testing or running projects locally (like `pipenv`'s virtualenv functionality), so maybe someone who's more experienced with it can chip in.

**Comment by lemonsaurus** [comment]
From what I can tell, poetry does not provide virtual environment integration at all, and expects you to handle this separately. Although it does "detect if you're in a virtual environment and install the packages accordingly". So in other words, it does not provide the functionality that pipenv does, and which I consider absolutely essential.

**Comment by jerbob** [comment]
I've done a bit of digging in [poetry issues](https://github.com/sdispater/poetry/issues/134#issuecomment-401228832), and it looks like it has commands for `poetry run` and `poetry shell` that expose its virtualenv, but they aren't really documented at all. I'll be able to do some experimenting with this tonight.

**Comment by jerbob** [comment]
Ah, looks like they're documented here: https://poetry.eustace.io/docs/cli/

**Comment by jerbob** [comment]
It looks like `poetry run` even supports scripts in the `pyproject.toml`, like pipenv does:
```toml
[tool.poetry.scripts]
my-script = "my_module:main"
```
```bash
poetry run my-script
```
https://poetry.eustace.io/docs/cli/#run
